name: Docker build
on:
  push:
    tags:
      - '*'
permissions:
  contents: write
  id-token: write
  packages: write
jobs:
  publish-pulumi-operator-kubernetes-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Publish pulumi-operator-kubernetes-job Docker Image
        uses: VaultVulp/gp-docker-action@1.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: pulumi-operator-kubernetes-job
          dockerfile: pulumi-operator-kubernetes-job/Dockerfile
          extract-git-tag: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
  publish-pulumi-operator-kubernetes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Publish pulumi-operator-kubernetes Docker Image
        uses: VaultVulp/gp-docker-action@1.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: pulumi-operator-kubernetes
          dockerfile: pulumi-operator-kubernetes/Dockerfile
          extract-git-tag: true
          cache-from: type=gha
          cache-to: type=gha,mode=max